name: deploy
on: [push]
jobs:


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: export DB=${{ secrets.DB }} && cd aiohttp_sample_auth && git pull && docker stop app ; docker-compose up  --build --force-recreate -d app